image: ansible/ansible:ubuntu1604py3
stages: 
  - test

test-lint:
  stage: test
  before_script:
    - echo "this is before"
    - python --version
  script:
    - echo "This is my script"
    - ansible --version