image: rackspacedot/python37-ansible27
stages: 
  - test

test-lint:
  stage: test
  before_script:
    - python --version
    - pip install -r build/requirements.txt
  script:
    - ansible --version
    - ansible-galaxy install -r build/requirements.yml -p roles -v
    - ansible-lint -v plays/* -x 404,401,301
