image: rackspacedot/python37-ansible27
stages: 
  - test

test-lint:
  stage: test
  before_script:
    - echo "this is before"
    - python --version
    - pip install -r requirements.txt
  script:
    - echo "This is my script"
    - ansible --version