image: rackspacedot/python37-ansible27

cache:
  key: "$CI_PROJECT_PATH_SLUG"
  paths:
    - roles/

before_script:
  - mv build/env_ansible.cfg ansible.cfg
  - python --version
  - pip install -r build/requirements.txt

stages: 
  - build
  - test

build_enviornment:
  stage: build
  script:
    - env && ls -alF
    - ansible --version
    - ansible-galaxy install -r build/requirements.yml -p roles -v

test-lint:
  stage: test
  dependencies: 
    - build_enviornment
  script:
    - env && ls -alF
    - ansible-lint -v plays/* -x 404,401,301,205

test-roles:
  stage: test
  dependencies: 
    - build_enviornment
  script: 
    - env && ls -alF
    - ansible-playbook roles/dotfiles/tests/test.yml --connection=local --force-handlers
  
  # Running on runner-72989761-project-11846906-concurrent-0 via runner-72989761-srm-1555468717-5b558c76...
  # Running on runner-72989761-project-11846906-concurrent-0 via runner-72989761-srm-1555468717-5b558c76...

Using docker image sha256:c40873e81b900f389139adf37702c112c2fe3ac278aca244ead44599f0bcec65 for rackspacedot/python37-ansible27 ...
Running on runner-72989761-project-11846906-concurrent-0 via runner-72989761-srm-1555468717-5b558c76...

Using docker image sha256:c40873e81b900f389139adf37702c112c2fe3ac278aca244ead44599f0bcec65 for rackspacedot/python37-ansible27 ...
Running on runner-ed2dce3a-project-11846906-concurrent-0 via runner-ed2dce3a-srm-1555468727-05bf8394...
  # Using docker image sha256:c40873e81b900f389139adf37702c112c2fe3ac278aca244ead44599f0bcec65 for rackspacedot/python37-ansible27 ...
