image: python:3.7.3

before_script:
  - mv build/env_ansible.cfg ansible.cfg
  - python --version
  - pip install -r build/requirements.txt
  - ansible-galaxy install -r build/requirements.yml -p roles -v

stages: 
  - build
  - test

build_enviornment:
  stage: build
  script:
    - env && ls -alF
    - ansible --version

test-lint:
  stage: test
  dependencies: 
    - build_enviornment
  script:
    - env && ls -alF
    - ansible-lint -v plays/* -x 404,401,301,205

test-roles:
  stage: test
  dependencies: 
    - build_enviornment
  script: 
    - env && ls -alF
    - ansible-playbook roles/dotfiles/tests/test.yml --connection=local --force-handlers
  