image: rackspacedot/python37-ansible27
stages: 
  - test

test-lint:
  stage: test
  before_script:
    - python --version
    - pip install -r requirements.txt
  script:
    - ansible --version
    - ansible-galaxy install -r requirements.yml -p roles -v
    - ansible-lint roles/dotfiles/tasks/*.yml -v
    - ansible-lint roles/dotfiles/handlers/*.yml -v