image: python:3.7.3

before_script:
  - python --version
  - pip install -r build/requirements.txt
  - mv build/env_ansible.cfg ansible.cfg
  - chmod -R go-wx $(pwd)
  - ansible-galaxy install -r build/requirements.yml -p roles -v
  - echo "redacted" > super_secret.vault_pass

stages: 
  - build
  - test

build_enviornment:
  stage: build
  script:
    - env && ls -alF
    - ansible --version

test-lint:
  stage: test
  dependencies: 
    - build_enviornment
  script:
    - env && ls -alF && ls -alF roles
    - ansible-lint -v plays/* -x 404,401,301,205

test-roles:
  stage: test
  dependencies: 
    - build_enviornment
  script: 
    - env && ls -alF
    - ansible-playbook tests/test_my_env.yml --connection=local --force-handlers -i tests/test_inventory
  